config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  get "home/index"
  root to: "home#index"

  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'

  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :shared_videos, only: %i( index new create )

  get "/*page" => "home#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/shared_video.rb
class SharedVideo < ApplicationRecord
  belongs_to :user

  validates :user_id, presence: true
  validates :url, presence: true
  validates :title, presence: true

  after_create :send_notification

  def send_notification
    NotificationBroadcastJob.perform_later(title, user.email)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :shared_videos

  before_save :downcase_email
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  private

  def downcase_email
    self.email = email.downcase
  end
end

app/models/video_embed_url_generator.rb
class VideoEmbedUrlGenerator
  REGEX_ID = %r{(?:youtube(?:-nocookie)?\.com\/(?:[^\/\n\s]+\/\S+\/|(?:v|e(?:mbed)?)\/|\S*?[?&]v=)|youtu\.be\/)([a-zA-Z0-9_-]{8,11})}.freeze

  attr_accessor :url
  attr_accessor :errors

  def initialize(url)
    @url = url
    @errors = []
  end

  def construct_iframe
    '<iframe '\
      'width=100% '\
      'height=300px '\
      'frameborder="0" '\
      'allow="autoplay; fullscreen" '\
      'allowfullscreen, '\
      "src='#{construct_url}'>"\
    '</iframe>'
  end

  def construct_url
    "https://www.youtube.com/embed/#{video_id}"
  end

  def valid?
    unless video_id
      @errors << 'Invalid URL'

      return false
    end

    true
  end

  private

  def video_id
    matched_result(REGEX_ID)
  end

  def matched_result(regex)
    match = regex.match(url)
    return false if match.blank? || match[1].blank?

    match[1]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include SessionsHelper

  private

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @shared_videos = SharedVideo.all.order(id: "DESC") .page params[:page]
  end

  def show
    render file: "public/404.html", status: :not_found unless valid_page?
  end

  private

  def valid_page?
    File.exist?(Pathname.new(Rails.root + "app/views/pages/#{params[:page]}.html.erb"))
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      flash.now[:success] = 'Login Successfully'
      log_in user
      redirect_to root_url
    else
      flash[:danger] = 'Invalid email/password combination'
      redirect_to login_path
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/shared_videos_controller.rb
class SharedVideosController < ApplicationController
  def index; end

  def create
    unless VideoEmbedUrlGenerator.new(shared_video_params[:url]).valid?
      flash[:danger] = "Invalid URL"

      return redirect_to root_url
    end

    current_user.shared_videos.create(shared_video_params) ? flash[:success] = "Share Youtube Video Successfully" : flash[:danger] = "Somthing Went Wrong !"

    redirect_to root_url
  end

  def shared_video_params
    params.require(:shared_video).permit(:title, :url)
  end
end

app/controllers/testings_controller.rb
class TestingsController < ApplicationController
	def new
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Create Account Successfully"
      log_in @user
      redirect_to root_url
    else
      flash_msg = []
      @user.errors.full_messages.each do |msg|
        flash_msg << msg
      end
      flash[:danger] = flash_msg.join(' & ')
      redirect_to signup_url
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "My Video"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def current_user?(user)
    user && user == current_user
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/shared_video_helper.rb
module SharedVideoHelper
  def youtube_iframe_for(shared_video)
    VideoEmbedUrlGenerator.new(shared_video.url).construct_iframe
  end
end

app/views/home/index.html.erb
<% provide(:title, "Home") %>
<p class="text-center" style="font-size: 30px; color: #000033; margin-top: 30px" id="shared_video">Shared Video</p><br>

<% if logged_in? %>
  <div class="modal fade" id="popup-notification" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="staticBackdropLabel">Notification: A new video is shared</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <h5>Title:</h5>
          <div id="title"></div>
          <hr>
          <h5>By User:</h5>
          <div id="by-user"></div>
        </div>
      </div>
    </div>
  </div>
<% end %>

<%= render @shared_videos %>

<div class="row justify-content-md-center">
  <div class="col col-lg-2">
    <div class="digg_pagination">
      <%= paginate @shared_videos %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="bg-light text-center text-white">
  <!-- Grid container -->
  <div class="container p-4 pb-0">
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Facebook -->
      <a
        class="btn btn-outline-success m-1"
        href="#!"
        role="button"
      ><i class="bi bi-facebook"></i
      ></a>

      <!-- Twitter -->
      <a
        class="btn btn-outline-success m-1"
        href="#!"
        role="button"
      ><i class="bi bi-twitter"></i
      ></a>

      <!-- Google -->
      <a
        class="btn btn-outline-success m-1"
        href="#!"
        role="button"
      ><i class="bi bi-google"></i
      ></a>

      <!-- Instagram -->
      <a
        class="btn btn-outline-success m-1"
        href="#!"
        role="button"
      ><i class="bi bi-instagram"></i
      ></a>

      <!-- Linkedin -->
      <a
        class="btn btn-outline-success m-1"
        href="#!"
        role="button"
      ><i class="bi bi-linkedin"></i
      ></a>
      <!-- Github -->
      <a
        class="btn btn-outline-success m-1"
        href="#!"
        role="button"
      ><i class="bi bi-github"></i
      ></a>
    </section>
    <!-- Section: Social media -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2022 Copyright:
    <a class="text-white" href="https://mdbootstrap.com/">@lampv318</a>
  </div>
  <!-- Copyright -->
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-lg-0" style="margin-left: 50px ">
        <li class="nav-item">
          <%= link_to root_path, id: "logo", style: 'color: gray' do %>
            <%= image_tag 'logo.png', style: 'width: 30px; height: 30px' %>
          <% end %>
        </li>
      </ul>
      <div class="d-flex">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <% if logged_in? %>
            <li class="nav-link">
              <p class="text-center" style="padding-top: 7px"><%= "#{current_user.email}" %></p>
            </li>
            <li class="nav-link">
              <%= link_to "Share Video", '#', class: 'btn btn-outline-success', 'data-bs-toggle': :modal, 'data-bs-target': "#staticBackdrop" %>
              <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                <div class="modal-dialog modal-lg">
                  <%= form_with(url: shared_videos_path, model: SharedVideo.new, local: true, method: :post) do |f| %>
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="staticBackdropLabel">Share a Youtube Video</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body">
                        <div class="row justify-content-md-center">
                          <div class="col col-lg-2">
                            <%= f.label :title, 'Title', style: 'padding-top: 6px' %>
                          </div>
                          <div class="col-md-8">
                            <%= f.text_field :title, class: 'form-control', placeholder: "Input Title", required: true %>
                          </div>
                        </div>
                        <hr>
                        <div class="row justify-content-md-center">
                          <div class="col col-lg-2">
                            <%= f.label :url, 'Youtube URL', style: 'padding-top: 6px' %>
                          </div>
                          <div class="col-md-8">
                            <%= f.text_field :url, class: 'form-control', placeholder: "Input Youtube URL", required: true %>
                          </div>
                        </div>
                      </div>
                      <div class="modal-footer">
                        <%= f.submit "Share", class: "btn btn-outline-success"%>
                      </div>
                    </div>
                  <% end %>
                </div>
              </div>
            </li>
            <li class="nav-link">
              <%= button_to "Log out", logout_path, method: :delete, class: 'btn btn-outline-success' %>
            </li>
          <% else %>
            <li class="nav-link">
              <%= link_to "Share Video", login_path, class: 'btn btn-outline-success' %>
            </li>
            <li class="nav-link">
              <%= link_to "Log in", login_path, class: 'btn btn-outline-success' %>
            </li>
            <li class="nav-link">
              <%= link_to "Register", signup_path, class: 'btn btn-outline-success' %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= favicon_link_tag asset_path('logo.png'), { sizes: '32x32' } %>

    <script src="https://code.jquery.com/jquery-3.7.0.js" integrity="sha256-JlqSTELeR4TLqP0OG9dxM7yDPqX1ox/HfgiSLBj8+kM=" crossorigin="anonymous"></script>
    <!-- FIXME: bootstrap-icons cdn -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css" integrity="sha384-b6lVK+yci+bfDmaY1u0zE8YYJt0TZxLEAFyYSLHId4xoVvsrQu3INevFKo+Xir8e" crossorigin="anonymous">
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared_videos/_shared_video.html.erb
<div class="container">
  <div class="row justify-content-md-center" style="margin-bottom: 20px">
    <div class="col col-lg-5">
      <%= raw youtube_iframe_for(shared_video) %>
    </div>
    <div class="col-lg-5">
      <div class="row">
        <div class="col-md-8">
          <h4><%= shared_video.title %></h4>
          shared by: <%= shared_video.user.email %>
        </div>
        <div class="col-md-4">
          <a
            class="btn btn-outline-success m-1"
            href="#!"
            role="button"
          ><i class="bi bi-hand-thumbs-up"></i
          ></a>
          <a
            class="btn btn-outline-success m-1"
            href="#!"
            role="button"
          ><i class="bi bi-hand-thumbs-down"></i
          ></a>
        </div>
      </div>
      90 <i class="bi bi-hand-thumbs-up-fill"></i>
      11 <i class="bi bi-hand-thumbs-down-fill"></i>
      <br>
      Description:
      <br>
      Párrafo de texto aleatorio: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    </div>
  </div>
</div>

app/views/testings/new.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>Web Speech API Example 2</title>
</head>
<body>
    <button id="button" onclick="toggleStartStop()"></button>
    <div style="border:dotted;padding:10px">
      <span id="final_span"></span>
      <span id="interim_span" style="color:grey"></span>
    </div>

    <script type="text/javascript">
      let recognizing;
      const recognition = new webkitSpeechRecognition();
      recognition.lang = "ja-JP";
      recognition.continuous = true;
      recognition.interimResults = true;
      reset();
      recognition.onend = reset;

      recognition.onresult = (event) => {
        let final = "";
        let interim = "";
        for (let i = 0; i < event.results.length; ++i) {
          if (event.results[i].isFinal) {
            final += event.results[i][0].transcript + "<br>";
          } else {
            interim += event.results[i][0].transcript;
          }
        }
        final_span.innerHTML = final;
        interim_span.innerHTML = interim;
      }

      function reset() {
        recognizing = false;
        button.innerHTML = "Click to Speak";
      }

      function toggleStartStop() {
        if (recognizing) {
          recognition.stop();
          reset();
        } else {
          recognition.start();
          recognizing = true;
          button.innerHTML = "Click to Stop";
          final_span.innerHTML = "";
          interim_span.innerHTML = "";
        }
      }
  </script>
</body>
</html>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<section class="vh-100" style="background-color: #white;">
  <div class="container h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-lg-12 col-xl-11">
        <div class="card text-black" style="border-radius: 25px;">
          <div class="card-body p-md-5">
            <div class="row justify-content-center">
              <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
                <p class="text-center h1 fw-bold mb-5 mx-1 mx-md-4 mt-4">Sign up</p>
                <%= form_for(@user, local: true) do |f| %>
                  <%= render 'shared/error_messages', object: f.object %>
                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="bi bi-person-circle me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <%= f.text_field :name, class: 'form-control', placeholder: "Your Name" %>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="bi bi-envelope me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <%= f.email_field :email, class: 'form-control', placeholder: "Your Email" %>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="bi bi-lock-fill me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <%= f.password_field :password, class: 'form-control', placeholder: "Password" %>
                    </div>
                  </div>

                  <div class="d-flex flex-row align-items-center mb-4">
                    <i class="bi bi-key-fill me-3 fa-fw"></i>
                    <div class="form-outline flex-fill mb-0">
                      <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "Repeat your password" %>
                    </div>
                  </div>

                  <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                    <%= f.submit "Register", class: "btn btn-outline-success btn-lg" %>
                  </div>
                <% end %>

              </div>
              <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">

                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                     class="img-fluid" alt="Sample image">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>